#!/usr/bin/env bun
/**
 * Parses openapi.json and generates src/commands.ts — a typed command registry
 * with parameter metadata derived from the OpenAPI spec.
 *
 * Run: bun run scripts/build-commands.ts
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = join(import.meta.dir, '..');
const SPEC_PATH = join(ROOT, 'openapi.json');
const OUTPUT_PATH = join(ROOT, 'src', 'commands.ts');

interface OpenAPISchema {
  info: { version: string };
  paths: Record<string, Record<string, OpenAPIOperation>>;
  components: { schemas: Record<string, unknown> };
}

interface OpenAPIOperation {
  operationId?: string;
  summary?: string;
  description?: string;
  requestBody?: {
    content?: {
      'application/json'?: {
        schema?: {
          properties?: Record<string, OpenAPIProperty>;
          required?: string[];
        };
      };
    };
  };
}

interface OpenAPIProperty {
  type?: string;
  description?: string;
  enum?: string[];
  'x-positional-index'?: number;
}
function main() {
  const spec: OpenAPISchema = JSON.parse(readFileSync(SPEC_PATH, 'utf-8'));
  const commands: CommandEntry[] = [];
  const actionCounts = new Map<string, number>();

  // Count how many tool groups use each action name (for ambiguity detection)
  for (const [path, methods] of Object.entries(spec.paths)) {
    for (const [method, op] of Object.entries(methods)) {
      if (method === 'get') continue;
      const match = path.match(/^\/api\/v2\/([^/]+)\/([^/]+)$/);
      if (!match) continue;
      const action = match[2];
      actionCounts.set(action, (actionCounts.get(action) || 0) + 1);
    }
  }

  for (const [path, methods] of Object.entries(spec.paths)) {
    for (const [method, op] of Object.entries(methods)) {
      if (method === 'get') continue;

      // Try two-segment pattern: /api/v2/{toolGroup}/{action}
      let toolGroup: string;
      let action: string;
      let isDirect = false;

      const twoSeg = path.match(/^\/api\/v2\/([^/]+)\/([^/]+)$/);
      if (twoSeg) {
        toolGroup = twoSeg[1];
        action = twoSeg[2];
      } else {
        // Try single-segment pattern: /api/v2/{toolGroup} (direct endpoint, no action)
        const oneSeg = path.match(/^\/api\/v2\/(spacemolt_[^/]+)$/);
        if (!oneSeg) continue;
        toolGroup = oneSeg[1];
        // Use the short name (strip spacemolt_ prefix) as the action
        action = toolGroup.replace(/^spacemolt_/, '');
        isDirect = true;
        // Also count for ambiguity
        actionCounts.set(action, (actionCounts.get(action) || 0) + 1);
      }

      const operationId = op.operationId || `${toolGroup}_${action}`;
      const summary = op.summary || action;

      // Extract params from request body schema
      const bodySchema = op.requestBody?.content?.['application/json']?.schema;
      const params: ParamEntry[] = [];
      const required = new Set(bodySchema?.required || []);

      if (bodySchema?.properties) {
        for (const [name, prop] of Object.entries(bodySchema.properties)) {
          params.push({
            name,
            type: prop.type || 'string',
            description: prop.description || '',
            required: required.has(name),
            positionalIndex: typeof prop['x-positional-index'] === 'number' ? prop['x-positional-index'] : -1,
            enumValues: prop.enum,
          });
        }
        // Sort by positional index (non-positional at the end)
        params.sort((a, b) => {
          const ai = a.positionalIndex === -1 ? 999 : a.positionalIndex;
          const bi = b.positionalIndex === -1 ? 999 : b.positionalIndex;
          return ai - bi;
        });
      }

      const isAmbiguous = (actionCounts.get(action) || 0) > 1;

      commands.push({
        toolGroup,
        action,
        operationId,
        summary,
        params,
        isAmbiguous,
        isDirect,
      });
    }
  }

  // Sort for stable output
  commands.sort((a, b) => {
    if (a.toolGroup !== b.toolGroup) return a.toolGroup.localeCompare(b.toolGroup);
    return a.action.localeCompare(b.action);
  });

  // Generate the output file
  const specVersion = spec.info?.version ?? 'unknown';
  const output = generateOutput(commands, specVersion);
  writeFileSync(OUTPUT_PATH, output);
  console.log(`Generated ${OUTPUT_PATH} with ${commands.length} commands (spec ${specVersion})`);
}

interface ParamEntry {
  name: string;
  type: string;
  description: string;
  required: boolean;
  positionalIndex: number;
  enumValues?: string[];
}

interface CommandEntry {
  toolGroup: string;
  action: string;
  operationId: string;
  summary: string;
  params: ParamEntry[];
  isAmbiguous: boolean;
  /** True if this is a direct endpoint (no action segment in URL) */
  isDirect: boolean;
}

function generateOutput(commands: CommandEntry[], specVersion: string): string {
  const lines: string[] = [];

  lines.push('// AUTO-GENERATED by scripts/build-commands.ts — DO NOT EDIT');
  lines.push('// Regenerate with: bun run generate');
  lines.push('');
  lines.push('export interface ParamDef {');
  lines.push('  name: string;');
  lines.push("  type: 'string' | 'integer' | 'boolean' | 'object' | 'array' | 'number';");
  lines.push('  description: string;');
  lines.push('  required: boolean;');
  lines.push('  /** Index in positional args, or -1 if key=value only */');
  lines.push('  positionalIndex: number;');
  lines.push('  enumValues?: string[];');
  lines.push('}');
  lines.push('');
  lines.push('export interface CommandMeta {');
  lines.push('  toolGroup: string;');
  lines.push('  action: string;');
  lines.push('  operationId: string;');
  lines.push('  summary: string;');
  lines.push('  params: ParamDef[];');
  lines.push('  /** True if the same action name exists in multiple tool groups */');
  lines.push('  isAmbiguous: boolean;');
  lines.push('  /** True if this is a direct endpoint (no action segment in URL) */');
  lines.push('  isDirect?: boolean;');
  lines.push('}');
  lines.push('');

  // Build the registry entries
  lines.push('const entries: [string, CommandMeta][] = [');
  for (const cmd of commands) {
    const params = JSON.stringify(cmd.params);
    lines.push(`  ["${cmd.toolGroup}/${cmd.action}", {`);
    lines.push(`    toolGroup: "${cmd.toolGroup}",`);
    lines.push(`    action: "${cmd.action}",`);
    lines.push(`    operationId: "${cmd.operationId}",`);
    lines.push(`    summary: ${JSON.stringify(cmd.summary)},`);
    lines.push(`    params: ${params},`);
    lines.push(`    isAmbiguous: ${cmd.isAmbiguous},`);
    if (cmd.isDirect) {
      lines.push(`    isDirect: true,`);
    }
    lines.push(`  }],`);
  }
  lines.push('];');
  lines.push('');

  lines.push('/** Full registry keyed by "toolGroup/action" */');
  lines.push('export const COMMAND_REGISTRY = new Map<string, CommandMeta>(entries);');
  lines.push('');

  // Build the short-name index (action -> toolGroup/action, only for non-ambiguous)
  lines.push('/** Short-name index: action -> "toolGroup/action" for non-ambiguous commands */');
  lines.push('export const SHORT_NAMES = new Map<string, string>();');
  lines.push('');
  lines.push('for (const [key, meta] of COMMAND_REGISTRY) {');
  lines.push('  if (!meta.isAmbiguous) {');
  lines.push('    SHORT_NAMES.set(meta.action, key);');
  lines.push('  }');
  lines.push('  const operationName = meta.operationId.replace(/^spacemolt_/, "");');
  lines.push('  if (operationName !== meta.action) {');
  lines.push('    SHORT_NAMES.set(operationName, key);');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Helper to list all tool groups
  const toolGroups = [...new Set(commands.map(c => c.toolGroup))].sort();
  lines.push(`export const TOOL_GROUPS = ${JSON.stringify(toolGroups)} as const;`);
  lines.push('');

  // Game API version this client was built against
  lines.push(`export const SPEC_VERSION = ${JSON.stringify(specVersion)};`);
  lines.push('');

  return lines.join('\n');
}

main();
